Ajoute un formulaire de connexion
LaurieBdt/Back-office-plaies pull request #4
Opened 2021-04-29 13:11 UTC by LaurieBdt

2021-04-29 13:42 UTC, AntoineCheron requested changes
C'est un bon départ !

N'oublie pas de corriger la police d'écriture en plus de ce qu'il y a dans mes commentaires.

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +    <title>Excercice</title>
```suggestion
    <title>Connexion</title>
```

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +    <form id="home">
Le formulaire, c'est juste pour les deux champs email et mot de passe + les deux boutons. Il faut pas qu'il entoure tout mais seulement la partie où y a les champs et boutons

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +        <section id="titre">
Cette fois ci on n'a pas de section, simplement une div.

```suggestion
        <div class="card-header">
```

Et c'est card-header qui va gérer la marge vers le bas

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +                <h1>Login</h1>
```suggestion
                <h1 class="card-title">Login</h1>
```

Traduit en français stp

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +        <section id="connexion">
La aussi pas une section

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +            <div id="email-form">
Remplace l'id "email-form" par une classe "form-input" pour pouvoir avoir le même style pour tous les champs du formulaire, n'importe où dans l'application.

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +            <div id="password-form">
Pas besoin de spécifier password-form, on peut utiliser une classe pour avoir le même style que l'input de l'adresse email

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +        <section id="button-login">
```suggestion
        <div class="form-buttons">
```

2021-04-29 13:42 UTC, AntoineCheron commented on src/index.html
> +            <input type="reset" value="Forgot your password" id="forgotyourpassword"/>
C'est pas un input mais plutôt un lien (`<a>`)

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    background-color: #E6EBEF;
J'aimerais bien que tu utilises les css-variables

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +#home {
Tu devrais pas utiliser d'id dans ton css pour cette page
```suggestion
.card{
```

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    height: 332px;
Je veux pas voir de hauteur en px, jamais jamais jamais. T'as pas besoin de définir la hauteur, ça va se faire tout seul si tu code bien

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +#titre {
Ne pas utiliser d'id ici

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    height: 10vh;
Toujours pas de hauteur à la main

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    background-color: white;
A retirer

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    border: 0px;
code dupliqué

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +#button-login {
Toujours pas besoin d'id

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +    height: 100px;
Toujours pas

2021-04-29 13:42 UTC, AntoineCheron commented on src/style.css
> +#forgotyourpassword {
pas nécessaire d'avoir un id, c'est juste un lien en fait (utiliser <a> comme je te disais)

2021-05-03 10:04 UTC, AntoineCheron requested changes

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.css
> +    src: url("../../../../lauriebodot/Library/Fonts/GothamRounded-Medium.otf") format("woff2");
Pas encore bon ici, il faut un chemin relatif au projet, pas un chemin spécifique à ton ordi

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.css
> +    height: 100vh;
min-heigth mais pas height sinon ta page ne pourra pas grandir.

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.css
> +    font-family: "Gotham";
Tu ne peux pas mettre une seule police. Renseigne toi sur les bonnes pratiques à ce sujet sur Google ;)

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.css
> +.principal {
Ce n'est pas clair comme nom de classe. Est-ce que tu peux chercher un nom qui décrit plus précisément l'élément stp ?

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.css
> +.retour {
Ici non plus ce n'est pas clair comme nom de classe. Est-ce que tu peux chercher un nom qui décrit plus précisément l'élément stp ?

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.html
> +    <title>Home</title>
Utilise un titre en français plutôt que Home pour être cohérent avec le contenu

2021-05-03 10:04 UTC, AntoineCheron commented on src/home.html
> +        <h1>Vous êtes connecter, bienvenue !</h1> <br>
Il y a une faute d'orthographe dans ce texte.

Autre point, `<br>` n'est pas nécessaire après un `<h...>`, tu peux le retirer.

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +    <div class="principal">
Même remarque ici pour le nom de la classe

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +            <div class="title">
Cette div est inutile

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +        <form class="form">
Le `form` ne devrait pas être dans la div `card-header` car il ne fait pas partie de l'en-tête mais du corps de la carte. Il faut donc une autre div `card-body` dans lequel tu pourras placer le `form` et les boutons.

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +            <div class="connexion">
`connexion` est trop flou comme nom de classe. D'ailleurs c'est une information sur la fonctionnalité du bloc, ça ressemble plus à un `id` qu'à une classe.

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +    <footer class="smarthealing">
Smarthealing c'est malheureusement pas un nom de classe clair, on ne sait pas de quoi sa parle. 

En plus, tu n'en as pas besoin, footer suffit a styliser l'élément.

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +        <p class="version">SmartHealing V1.0.1</p>
`version` décrit plus la fonctionnalité que le caractère technique de l'élément. Ca devrait plutôt etre un `id`. 

Pour que ce soit plus clair `version-text` serait plus adapté.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    --main-bg-color: #E6EBEF;
C'est bien comme ça qu'il faut utiliser des variables ! 👍

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    font-family: "Gotham";
Ici aussi c'est trop peu de juste mettre Gotham. Renseigne toi sur les bonnes pratiques.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    height: 100vh;
Pareil que pour l'autre fichier css

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +.principal{
Pareil ici pour le nommage

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    background-color: white;
La couleur de fond devrait être affectée à toute la carte, pas seulement à son header. Le header ne devrait pas avoir de couleur de fond, sauf si elle est différente du reste de la carte.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +.title {
Tu ne devrais pas avoir recourt à cette classe, comme je te l'ai dis dans mon commentaire sur le fichier html. Essaie de la retirer et de gérer ce padding dans le `card-header`.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +.card-title {
Il faudrait deux blocs CSS ici plutôt qu'un seul. Un pour `.card-title` qui définit les espacements et le positionnement, et un autre `h1 .card-title`qui style la police si on utilise un h1. On pourrait imaginer utiliser d'autres tailles si on utilisait un h2 dans la div `card-title`.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +.connexion {
Si c'est juste pour affecter une taille de police, il faut un nom plus technique, par exemple `text-medium`, ou `text-small` selon comment tu veux gérer tes tailles de police.

2021-05-03 10:04 UTC, AntoineCheron commented on src/index.html
> +                    <input type="email" name="email" placeholder="Adresse e-mail" class="style-input"/>
la classe `style-input` est inutile, en css le sélecteur `.form-input > input` sera suffisant

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +.style-input{
```suggestion
.form-input > input{
```

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    width: 422px;
Tu ne devrais pas fixer la largeur en px. Utilise plutôt `width: 100%` et joue sur les marges.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    color:#B3C1CD;
Il faudrait utiliser une variable css ici

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    border: 1px solid #00A6C8;
Ici aussi il faudrait une variable css, et il faudrait placer la bordure à l'intérieur de l'input.

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    margin-top: 34px;
Pas de `margin-top`, c'est toujours l'élément d'au dessus qui pousse vers le bas

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    margin-bottom: 25px;
Bizarre ce `25px`, tout devrait être multiple de `4`, au moins de 2. Utilise plutôt `24px`

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    margin-bottom: 24px;
Tu ne devrais pas gérer l'espacement ici mais plutôt dans la boite qui contient les boutons. Surtout que pour gérer tes alignements tu as les flexbox

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    font-size: 14px;
Ca ça pourrait être pour tous les `a` du document

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    color: #00A6C8;
css-variable

2021-05-03 10:04 UTC, AntoineCheron commented on src/style.css
> +    color: #B3C1CD;
css-variable

2021-05-05 13:21 UTC, LaurieBdt commented on src/home.css
> +    font-family: "Gotham";
Je n'est pas compris je doit faire plusieurs font-family? genre comme sa  
```suggestion
    font-family: "Roboto", "Helvetica", "Arial", sans-serif;
```

2021-05-05 14:06 UTC, LaurieBdt commented on src/style.css
> +    background-color: white;
C'était juste pour encadré le texte, une question de desgin la couleur de fond

2021-05-05 14:50 UTC, LaurieBdt commented on src/style.css
> +    background-color: white;
Card est pas le header, c'est comme si c'était le body de la card

2021-05-05 14:58 UTC, AntoineCheron commented on src/style.css
> +    background-color: white;
Tu as changé la classe, du coup comme ça en effet c'est parfait.

2021-05-05 15:03 UTC, AntoineCheron requested changes

2021-05-05 15:03 UTC, AntoineCheron commented on src/style.css
> +}
C'est bizarre de mettre ce padding sur des paragraph. D'autant plus que dans `form-buttons` je m'attend à voir des boutons et pas des paragraphes

2021-05-05 15:03 UTC, AntoineCheron commented on src/style.css
> +
Tu as trop de sauts de ligne ici

2021-05-05 15:03 UTC, AntoineCheron commented on src/style.css
> +.version-text{
```suggestion
#version-text{
```

2021-05-05 15:03 UTC, AntoineCheron commented on src/style.css
>  }
A supprimer, `#login` n'est jamais utilisé dans le doc html

2021-05-05 15:03 UTC, AntoineCheron commented on src/index.html
> +    <div class="card-header">
Il manque un tab d'indentation à partir d'ici. Les deux divs sont l'une en dessous de l'autre alors que card-header devrait être décalée

2021-05-05 15:15 UTC, LaurieBdt commented on src/style.css
> +}
Cela veux dire que je les converti en boutton? parce que je ne suis pas sur d'avoir compris

2021-05-05 15:15 UTC, LaurieBdt commented on src/style.css
>  }
je ne comprend pas comment je peut faire parce que les boutton son different un avec une bordure l'autre sens un qui et color blue et l'autre white si je leur met pas des id pour dire qu'il sont unique je ne comprend comment faire je n'est pas d'autre solution

2021-05-05 15:36 UTC, AntoineCheron approved these changes

2021-05-05 15:52 UTC, merged