Nouvelle page home
LaurieBdt/Back-office-plaies pull request #5
Opened 2021-05-11 16:17 UTC by LaurieBdt

2021-05-12 11:18 UTC, AntoineCheron requested changes
C'est pas mal du tout ! 

Je t'ai mis quelques modifications à faire. 

Pense à supprimer les fichiers .zip qui sont dans ton projet. Il n'en faut pas. Tu peux par exemple ajouter une entrée dans le .gitignore, je te laisse regarder sur Google comment faire. 

Il faut aussi penser à gérer le hover du bouton de connexion. C'était dans la liste de mes remarques sur Slack ;)

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    background-color: #EDEDED;
Utilise une CSS variable ici

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    background-color: #ffffff;
Utilise une CSS variable ici aussi stp. Tu pourras l'appeler --white

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    width: 85%;
Pourquoi 85% ? 
Dès que tu utilises autre chose que 100% ou calc(100% - un_nombre) c'est bizarre. 

Qu'est ce que tu cherches à faire dans ce cas là ?

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +
Y a beaucoup de sauts de ligne pour rien ici, y'a que 2 propriétés

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    background-color: #FFFFFF;
Ici utilises la css variable --white que tu auras créée

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    border: white;
Si le fond est blanc c'est bizarre que tu aie besoin d'une bordure blanche. 

Elle te sert à quoi ?

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    font-family: "Gotham", "Arial", sans-serif;
Si la police est la même que partout dans l'app, tu ne devrais pas la redéfinir sur une classe. 

Si jamais elle ne s'applique pas, applique la sur l'élément button mais pas sûr la classe.

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +.button-general span {
Au lieu de ce sélecteur, utilise une classe "button-left-icon" pour mettre sur le span qui entoure le +

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    background-color: #f0f0ee;
Utilise une CSS variable

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +    display: flex;
Inutile si tu n'appliques pas d'autres propriétés

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +.button-information {
Ce n'est pas un bouton

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.html
> +                        <span>+</span> Traitement général
N'oublie pas d'utiliser le SVG pour le + ici

2021-05-12 11:18 UTC, AntoineCheron commented on src/home.css
> +.rond {
En anglais c'est plutôt .circle

2021-05-12 11:18 UTC, AntoineCheron commented on src/image/Catagory/General-treatment/Missing/Arrow/Vector.svg
> +<svg width="12" height="6" viewBox="0 0 12 6" fill="none" xmlns="http://www.w3.org/2000/svg">
Appelle plutôt le fichier "plus-sign.svg" et mets le dans "src/image"

2021-05-12 11:18 UTC, AntoineCheron commented on src/style.css
>      --main-bg-color3: #B3C1CD;
Ici aussi il faut changer les noms des variables

2021-05-12 11:18 UTC, AntoineCheron commented on src/style.css
>      font-family: "Gotham", "Arial", sans-serif;
Ici aussi il faut gérer correctement font family

2021-05-15 17:53 UTC, LaurieBdt commented on src/home.css
> +    width: 85%;
Je voulais juste que le container avait la meme taille que les blocs je ne sais pas pourquoi je trouvais sa logique j'ai mit 100% par ce que sa ne change rien

2021-05-15 17:53 UTC, LaurieBdt commented on src/home.css
> +    border: white;
Si je ne met pas de border definit blanche, elle me met la bordure en noir automatiquement voila pourquoi

2021-05-15 17:53 UTC, LaurieBdt commented on src/home.css
> +.button-information {
Je les mit en tant qu'icone

2021-05-17 10:58 UTC, AntoineCheron requested changes

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    --grey-white: #EDEDED;
grey-white c'est bizarre comme nom

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    font-weight: 800;
Pourquoi tu as mis 800 ici ? C'est très bizarre comme valeur par défaut.

Dans le cas que tu développes tu ne devrais pas définir `font-weight` sur `body`

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    font-style: normal;
Inutile c'est déjà la valeur par défaut

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    font-weight: 400;
A supprimer après avoir supprimé `font-weight: 800` sur body

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    color:var(--grey);
```suggestion
    color: var(--grey);
```

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +.navbar-container p{
Toujours pas ok pour moi ce genre de sélecteur, c'est trop spécifique. Attribue une classe aux `p`

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +.text-style {
Très flou comme nom de classe.

En plus en voyant son contenu tu n'as pas besoin d'une classe pour définir ces propriétés sur du texte. Il suffit de les placer au bon endroit pour que, par défaut, ça s'applique sur le texte.

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    width:calc(100% - 60px);
```suggestion
    width: calc(100% - 60px);
```

Fais attention à toujours mettre un espace après les `:`, c'est plus facile à lire

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    border: var(--white);
Même couleur que background du coup pas besoin je pense

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    font-style: normal;
Inutile il me semble

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    display: flex;
Donc faut le supprimer

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    padding: 8px;
C'est bizarre un padding pour une icone

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +.icon-check {
C'est quasiment un copier/coller de `.icon-en-traitement`. Au lieu d'avoir `.icon-en-traitement` et `.icon-check` tu devrais avoir 3 classes (donc une de plus) qui n'ont aucune propriété identiques (donc aucun copier/coller). 

Bonne chance pour cet exercice :)

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +.category-card-title-langue{
```suggestion
.category-card-language {
```

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    font-style: normal;
Tu ne devrais pas avoir à définir ces propriétés là, c'est normalement des valeurs par défaut

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +}*/
Supprime le si tu ne l'utilises pas

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    width: 464px;
Pas de largeur fixe

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +.fleche-information-suplementaire-2 img{
Je t'avais demandé "plus jamais de -1 ou -2 etc.." et bim j'en vois un. Faut le supprimer stp

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.css
> +    margin-left: -18px;
Oulalala une marge négative. A ne jamais jamais faire, ça montre qu'il y a un problème dans ce que t'as codé car ce n'est jamais nécessaire de faire ça. Il faut trouver une autre solution.

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                <p>Pressure relief</p>
Ici il faudrait que les `<p>` soient dans des `<div>`, ça représenterait mieux la structure et ça sera plus simple à styliser.

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                        <span><img src="./image/plus-sign.svg" alt=""></span> Traitement général
Pourquoi tu utilises un span ici ?

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                                <img src="./image/Vector.svg" alt="icon-fleche">
Renomme le fichier `Vector.svg` en `arrow-down.svg` ;) (si la flèche va bien vers le bas)

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                <div class="cards-container">
Pas besoin d'un deuxième `cards-container`. Il faut un seul conteneur pour toutes les cartes.

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                                <img src="./image/check.svg" alt="iconcheck">
Le `alt` n'est pas assez explicite, il faudrait mettre des espaces dedans

2021-05-17 10:58 UTC, AntoineCheron commented on src/home.html
> +                                <p class="category-card-translation">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa qu
Ca ça ne marchera pas. Je t'avais donné deux contraintes : 

1. Il faut pouvoir cacher toutes les traductions (sauf la toute première en anglais), en mettant `display: none` sur un seul élément HTML ➜ avec le code actuel c'est impossible
2. Il ne fallait pas modifier le code de la carte que tu as copié/collé ➜ tu l'as modifié en déplaçant la `div class="card-content"` et en ajoutant du contenu dans la `div class="text-container"`. 

Il faut donc que tu trouves une autre solution qui respecte ces deux contraintes. La seule div dans laquelle tu as le droit d'ajouter du contenu c'est `div class="card-content"`, et elle doit être placée au même endroit que pour la première carte qui est juste au dessus.

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +    font-weight: 400;
Je n'est pas compris, a supprimer apres avoir supprimer :/

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +.text-style {
Je n'est pas trop compris, le bon endroit ou le placer

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +    padding: 8px;
Je sais, mais c'est la seule solution que j'ai trouver pour ne pas que le rond sois ecraser par les autre div

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +.icon-check {
Je ne vois pas comment je pourrais avoir 3 classe, euh j'avoue qu'avant je utilisais que des id du coup j'avais pas ce problème, faudrai que tu m'explique comme utiliser plusieurs classe parce que sur internet je n'est pas trouver

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +    width: 464px;
j'ai mit une largeur fixe euh bas parce que je ne peut pas savoir combien font 464px en % '-'...

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +    margin-left: -18px;
Euh oui mais je crois qu'il ya un probleme parce que je ne trouve pas d'autre solution

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.css
> +.fleche-information-suplementaire-2 img{
J'ai mit 1 2 Parce qu'il non pas les même taille alors a par 1 et 2 je ne sais pas comment faire

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.html
> +                        <span><img src="./image/plus-sign.svg" alt=""></span> Traitement général
Bas je ne sais pas j'ai cru qu'on m'était un span quand on a une image qui ressemble a un logo

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.html
> +                                <img src="./image/Vector.svg" alt="icon-fleche">
J'ai renommé l'image mais elle ce s'affiche plus

2021-05-18 12:32 UTC, LaurieBdt commented on src/home.html
> +                                <p class="category-card-translation">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa qu
J'ai compris le permier point mais pas reste o.O

2021-06-21 10:45 UTC, merged